### ISSUE TITLE
Decide on framework for running things concurrently

### ISSUE THREAD

**Issue by surminus** [surminus/viaduct#11]

**Comment by surminus** [comment]
One way this could work is to reshape how it currently runs:

You add resources using the standard syntax, eg `v.File{...}.Create()`. Instead of actually running these commands, it stores what it should run somewhere (in memory/temporarily file). 

You can then use `v.Compile()` (or something similar) to actually run everything in order.

To enable concurrency, you can just set `v.Parallel()` somewhere along the way.

Perhaps we create a new object each time:

```
foo := v.New()
// foo := v.NewParallel()

foo.File{...}.Create()
foo.Run()
```

Doing it this way also means you could add dependencies in:
```
dir := foo.Dir{...}.Create()

foo.File{
   ...,
   DependsOn: dir,
}
```
This would probably require that each resource is a type (eg `viaduct.Resource`).

**Comment by prologic** [comment]
I kind of like the idea of everything being a `Resource` -- In fact this _should_ probably be an interface type? It _would_ probably make the code you write more "declarative" with collections of resources which you finally call `.Run(0` on to actually perform checks/balances and create/delete/update as appropriate?

**Comment by surminus** [comment]
Thank you for commenting :) I think an interface makes a lot of sense here and would make a clearer definition for adding new resource types. I think it probably makes sense regardless of whether I implement the larger changes around compilation of resources etc.

**Comment by surminus** [comment]
Added concurrency support and reshaped how it works in https://github.com/surminus/viaduct/commit/b382a5fd960dae5e54e78f2b7c51fde54fa19bf3. 

Still a bunch of things I want to tidy up and polish, make it cleaner to add resources; more descriptive resource IDs; make it easier to add new resource types in general, and maybe tidier syntax for adding dependencies. But in general the basic structure is there, so closing this for now.
